### ISSUE TITLE
The extension could not be loaded because it requires a later version of Java

### ISSUE THREAD

**Issue by sfttw** [mystech7/Burp-Hunter#4]
Hi, I'm having a trouble loading Burp-Hunter inside Burp since upgrading to the latest version of Java (Version 8 Update 161 (build 1.8.0_161-b12)) on OS X
```
java.lang.UnsupportedClassVersionError: burp/BurpExtender : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:278)
	at burp.sue.a(Unknown Source)
	at burp.sue.<init>(Unknown Source)
	at burp.mn.a(Unknown Source)
	at burp.ooh.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
The extension could not be loaded because it requires a later version of Java. To use this extension you will need to start Burp with the required or later Java version.
```

When trying to compile from source I get this error:

```
src/burp/BurpExtender.java:54: error: illegal start of expression
        SwingUtilities.invokeLater(() -> {
                                    ^
src/burp/BurpExtender.java:54: error: illegal start of expression
        SwingUtilities.invokeLater(() -> {
                                       ^
src/burp/BurpExtender.java:54: error: illegal start of expression
        SwingUtilities.invokeLater(() -> {
                                         ^
src/burp/BurpExtender.java:54: error: ';' expected
        SwingUtilities.invokeLater(() -> {

[...]
```

**Comment by sfttw** [comment]
This was my fault, OS X was still running the old version of Java because I didn't install the Development Kit. Apologizes.
